### ISSUE TITLE
WebDriver\Exception\UnknownException

### ISSUE THREAD

**Issue by rgembalik** [minkphp/docs#24]
I am having problem running mink + behat combo. The scenario looks as follows:

``` behat
@javascript @insulated
Feature: Login
  Scenario: Login valid
    Given I am on "/auth/login"
    When I fill in the following:
      | email | xxx |
      | pass_hash | xxx |
    And I press "Sign in"
    Then I should be on "/dashboard"

  Scenario: Login invalid
    Given I am on "/auth/login"
    When I fill in the following:
      | email | yyy |
      | pass_hash | yyy |
    And I press "Sign in"
    Then I should see "Wrong e-mail or password."
```

And I get the following result
https://gist.github.com/rgembalik/fe7e8dbbe53d2ee8669b

behat.yml looks like this:

```
default:
    extensions:
        mink_extension.phar:
            mink_loader: mink.phar
            base_url: http://localhost/testpage
            goutte: ~
            selenium2:
                wd_host: http://127.0.0.1:4444/wd/hub
                capabilities:
                  version: ''
```

Selenium session is created and firefox is launching, but no url is inserted. Sessions stays registered in selenium (it is visible under http://127.0.0.1:4444/wd/hub).

Any idea and/or suggestions?

EDIT:
BTW, when I try it without `@javascript @insulated` it works just fine and the test passes. I have problems only with selenium.
